# Generated by Django 4.2.16 on 2024-12-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_usuarios_correo_usuarios_nombre_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='Nada', max_length=1000),
        ),
    ]
