# Generated by Django 4.2.16 on 2024-12-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='created',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Creacion: '),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='update',
            field=models.DateField(auto_now=True, verbose_name='Ultima Modificacion: '),
        ),
    ]
