# Generated by Django 4.2.16 on 2024-12-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_usuarios_id_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='estado',
            field=models.IntegerField(blank=True, null=True, verbose_name='estado'),
        ),
    ]
