# Generated by Django 4.2.16 on 2024-12-03 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_usuarios_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materiales',
            old_name='Mombre',
            new_name='Nombre',
        ),
    ]
