# Generated by Django 4.2.16 on 2024-12-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_rename_mombre_materiales_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='created',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Creacion: '),
        ),
        migrations.AlterField(
            model_name='docente',
            name='update',
            field=models.DateField(auto_now=True, verbose_name='Ultima Modificacion:'),
        ),
    ]
